import { Routes } from '@angular/router';
import { BookingComponent } from './booking/booking.component';
import { HomeComponent } from './home/home.component';
import { PackagesComponent } from './packages/packages.component';
import { HouseComponent } from './house/house.component';
import { RoomsComponent } from './rooms/rooms.component';
import { ActivitiesComponent } from './activities/activities.component';
import { ContactComponent } from './contact/contact.component';
import { PrivacyPolicyComponent } from './privacy-policy/privacy-policy.component';
import { SurfGuidingComponent } from './surf-guiding/surf-guiding.component';
import { SurfLessonsComponent } from './surf-lessons/surf-lessons.component';
import { OtherSurfExperiencesComponent } from './other-surf-experiences/other-surf-experiences.component';
import { TheMoonRoomComponent } from './the-moon-room/the-moon-room.component';
import { TheCaveRoomComponent } from './the-cave-room/the-cave-room.component';
import { OffshoreRoomComponent } from './offshore-room/offshore-room.component';
import { OnshoreRoomComponent } from './onshore-room/onshore-room.component';
import { FaqComponent } from './faq/faq.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'booking', component: BookingComponent },
  { path: 'packages', component: PackagesComponent },
  { path: 'house', component: HouseComponent },
  { path: 'rooms', component: RoomsComponent },
  { path: 'rooms/the-moon', component: TheMoonRoomComponent },
  { path: 'rooms/the-cave', component: TheCaveRoomComponent },
  { path: 'rooms/offshore', component: OffshoreRoomComponent },
  { path: 'rooms/onshore', component: OnshoreRoomComponent },
  { path: 'activities', component: ActivitiesComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'privacy-policy', component: PrivacyPolicyComponent },
  { path: 'faq', component: FaqComponent },
  { path: 'packages/surf-lessons', component: SurfLessonsComponent },
  { path: 'packages/surf-guiding', component: SurfGuidingComponent },
  { path: 'packages/other-surf-experiences', component: OtherSurfExperiencesComponent }
];
